TRANSLATIONS = {
    "TR": {
        "app_name": "Dosya Şifreleme Uygulaması",
        "title": "Dosya Şifreleme",
        "file_button": "📂 Dosya Seç",
        "file_placeholder": "Seçilen dosya yolu...",
        "password_placeholder": "Şifre giriniz...",
        "encrypt_button": "🔒 Şifrele",
        "decrypt_button": "🔓 Şifre Çöz",
        "processing": "İşlem devam ediyor... (%{})",
        "completed": "İşlem tamamlandı!",
        "error_title": "Hata",
        "success_title": "Başarılı",
        "success_message": "İşlem tamamlandı!\nDosya kaydedildi: {}",
        "file_select_title": "Dosya Seç",
        "delete_file_title": "Dosya Silme",
        "delete_file_message": "Orijinal dosyayı silmek ister misiniz?",
        "file_deleted": "Orijinal dosya silindi.",
        "warning_title": "Uyarı",
        "file_delete_error": "Dosya silinirken bir hata oluştu: {}",
        "input_required": "Lütfen dosya ve şifre giriniz!",
        "processing_started": "İşlem başlatılıyor...",
        "file_filter": "Tüm Dosyalar (*.*)"
    },
    "EN": {
        "app_name": "File Encryption Application",
        "title": "File Encryption",
        "file_button": "📂 Select File",
        "file_placeholder": "Selected file path...",
        "password_placeholder": "Enter password...",
        "encrypt_button": "🔒 Encrypt",
        "decrypt_button": "🔓 Decrypt",
        "processing": "Processing... (%{})",
        "completed": "Operation completed!",
        "error_title": "Error",
        "success_title": "Success",
        "success_message": "Operation completed!\nFile saved: {}",
        "file_select_title": "Select File",
        "delete_file_title": "Delete File",
        "delete_file_message": "Do you want to delete the original file?",
        "file_deleted": "Original file deleted.",
        "warning_title": "Warning",
        "file_delete_error": "An error occurred while deleting the file: {}",
        "input_required": "Please select a file and enter a password!",
        "processing_started": "Starting process...",
        "file_filter": "All Files (*.*)"
    }
} 